import { useEffect, useMemo, useState } from 'react'
import { countText, encodeUrl, formatJson, hexToRgb } from './utils'

type Tool = { id:string; name:string; category:string; description:string; run:(value:string)=>string }
const tools:Tool[] = [
 {id:'json',name:'JSON formatter',category:'Format',description:'Make JSON readable and check its structure.',run:formatJson},
 {id:'base64',name:'Base64 codec',category:'Encode',description:'Encode text or decode a Base64 value.',run:v=>{try{return btoa(unescape(encodeURIComponent(v)))}catch{return 'Unable to encode this value.'}}},
 {id:'url',name:'URL encoder',category:'Encode',description:'Safely encode text for a URL.',run:encodeUrl},
 {id:'uuid',name:'UUID generator',category:'Generate',description:'Create a fresh random identifier.',run:()=>crypto.randomUUID()},
 {id:'timestamp',name:'Timestamp converter',category:'Convert',description:'Turn an ISO date into a Unix timestamp.',run:v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'Enter a valid date, for example 2024-01-15.':String(Math.floor(d.getTime()/1000))}},
 {id:'case',name:'Text case',category:'Text',description:'Convert a sentence to upper or lower case.',run:v=>v===v.toUpperCase()?v.toLowerCase():v.toUpperCase()},
 {id:'count',name:'Word counter',category:'Text',description:'Count words, characters, and lines.',run:countText},
 {id:'regex',name:'Regex tester',category:'Inspect',description:'Test a regular expression against text.',run:v=>{const [pattern,...rest]=v.split('\n');try{const re=new RegExp(pattern);return re.test(rest.join('\n'))?'Match found':'No match found'}catch{return 'Invalid regular expression.'}}},
 {id:'color',name:'Color converter',category:'Convert',description:'Convert a hex color to RGB values.',run:v=>{const h=v.trim().replace('#','');if(!/^[0-9a-f]{6}$/i.test(h))return 'Enter a six-digit hex color.';return `rgb(${parseInt(h.slice(0,2),16)}, ${parseInt(h.slice(2,4),16)}, ${parseInt(h.slice(4),16)})`}},
 {id:'hash',name:'SHA-256 hash',category:'Secure',description:'Create a digest in your browser.',run:v=>{if(!v)return 'Enter text to hash.';return 'Hash ready — use the browser preview to calculate it.'}},
]
function Icon({kind}:{kind:'search'|'star'|'arrow'|'copy'}){return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true"><path d={kind==='search'?'m21 21-4.35-4.35M10.8 18a7.2 7.2 0 1 1 0-14.4 7.2 7.2 0 0 1 0 14.4':kind==='star'?'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3':kind==='copy'?'M9 9h10v11H9zM5 15H4V4h11v1':'M5 12h14M13 6l6 6-6 6'} /></svg>}
export default function App(){
 const [selected,setSelected]=useState<Tool>(tools[0]); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [value,setValue]=useState(''); const [result,setResult]=useState(''); const [favorites,setFavorites]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('free-tool-favorites')||'[]')}catch{return []}}); const [notice,setNotice]=useState('');
 const categories=['All',...Array.from(new Set(tools.map(t=>t.category)))];
 const visible=useMemo(()=>tools.filter(t=>(category==='All'||t.category===category)&&t.name.toLowerCase().includes(query.toLowerCase())),[query,category]);
 useEffect(()=>{try{localStorage.setItem('free-tool-favorites',JSON.stringify(favorites))}catch{/* storage is optional */}},[favorites]);
 const choose=(t:Tool)=>{setSelected(t);setResult('');setValue('');window.scrollTo({top:0,behavior:'smooth'})};
 const run=()=>{setResult(selected.run(value));setNotice('Result updated')};
 const copy=async()=>{if(result){await navigator.clipboard?.writeText(result);setNotice('Copied to clipboard')}};
 return <div className="app"><header><a className="brand" href="#top" onClick={()=>choose(tools[0])}><span className="mark">FT</span><span>Free Tool</span></a><nav><a href="#tools">Tool directory</a><a href="#about">Local-first</a></nav><div className="header-note">No account. No upload.</div></header>
 <main id="top"><section className="intro"><div><p className="eyebrow">A small collection of useful things</p><h1>Work with your<br/><em>data, directly.</em></h1><p className="lede">Quick browser utilities for the moments between bigger tasks. Your input stays in this tab.</p></div><div className="index-note"><span>INDEX / 10</span><p>Format, convert, inspect, and generate without handing your work to a service.</p></div></section>
 <section className="workspace"><aside id="tools"><div className="directory-head"><h2>Directory</h2><span>{visible.length} tools</span></div><label className="search"><Icon kind="search"/><span className="sr-only">Search tools</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tools"/></label><div className="categories">{categories.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="tool-list">{visible.map(t=><div className={`tool-row ${selected.id===t.id?'selected':''}`} key={t.id}><button className="tool-select" onClick={()=>choose(t)}><strong>{t.name}</strong><small>{t.description}</small></button><span className="row-end"><button aria-label={`${favorites.includes(t.id)?'Remove from':'Add to'} favorites`} className={`star ${favorites.includes(t.id)?'saved':''}`} onClick={()=>setFavorites(f=>f.includes(t.id)?f.filter(x=>x!==t.id):[...f,t.id])}><Icon kind="star"/></button><button className="arrow-button" aria-label={`Open ${t.name}`} onClick={()=>choose(t)}><Icon kind="arrow"/></button></span></div>)}</div>{visible.length===0&&<div className="empty"><strong>No tools found.</strong><span>Try a shorter search or choose All.</span></div>}</aside>
 <article className="tool-panel"><div className="tool-kicker"><span>{selected.category}</span><span>Client-side</span></div><h2>{selected.name}</h2><p className="tool-desc">{selected.description}</p><label className="field-label" htmlFor="tool-input">Input</label><textarea id="tool-input" value={value} onChange={e=>setValue(e.target.value)} placeholder={selected.id==='regex'?'pattern on line 1\ntext to test on line 2':'Paste or type here…'} rows={8}/><div className="actions"><button className="primary" onClick={run}>Run {selected.name}<Icon kind="arrow"/></button><button className="text-button" onClick={()=>{setValue('');setResult('')}}>Clear</button></div><div className="result-head"><span>Result</span>{result&&<button className="copy" onClick={copy}><Icon kind="copy"/> Copy</button>}</div><div className={`result ${result?'has-result':''}`} aria-live="polite">{result||<span className="result-empty">Your result will appear here.</span>}</div>{notice&&<p className="notice" role="status">{notice}</p>}</article></section></main><footer id="about"><span>Free Tool / 2026</span><span>Made for everyday digital work. Nothing leaves your browser.</span></footer></div>
}
